name: evodiff
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cudatoolkit=11.8
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - tqdm=4.66.1
  - biopython=1.81
  - scipy=1.11.2
  - pip
  - pip:
# Attention!! EvoDiff must be installed from source
# Please see README.md for instructions